#!/usr/bin/env bash

set -ex

cd build

if [ -d linux/boot ];then exit 0; fi

git clone --depth=1 https://github.com/raspberrypi/firmware

cd firmware/boot

rm {*.dtb,*.img}

touch pi64-config-debug.txt
