#!/usr/bin/env bash

set -ex

source .env || true

if [ -n "$skip_build_kernel" ];then exit 0; fi

cd build

git clone --depth=1 https://github.com/raspberrypi/firmware

cd firmware/boot

rm {*.dtb,*.img}

touch pi64-config-debug.txt
