#!/usr/bin/env bash

set -ex

mkdir -p build && cd build

if [ -d linux/usr/src ];then exit 0; fi

git clone --depth=1 -b rpi-5.3.y https://github.com/raspberrypi/linux.git linux-src

cd linux-src

# cp ../../make/kernel-config.txt ./.config

make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcmrpi3_defconfig # olddefconfig

echo "
CONFIG_MEMCG=y
CONFIG_CGROUP_PIDS=y
CONFIG_BLK_CGROUP=y
CONFIG_BLK_DEV_THROTTLING=y
CONFIG_CFQ_GROUP_IOSCHED=y
CONFIG_CGROUP_PERF=y
CONFIG_CGROUP_NET_PRIO=y
CONFIG_CFS_BANDWIDTH=y
CONFIG_INET_XFRM_MODE_TRANSPORT=m
" | tee -a .config

make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- olddefconfig

make -j $(nproc) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

kernelversion=$(make -s kernelversion)

echo "kernelversion=${kernelversion}" > ../.env
