#!/usr/bin/env bash

set -ex

cd build

release=$(date +"%Y-%m-%d")

git tag $release || true
git push origin $release || true

github-release release --user ${GITHUB_USER:-khs1994} --repo pi64 --tag $release --draft || true

for version in "lite" "desktop" ; do
    github-release upload --user ${GITHUB_USER:-khs1994} --repo pi64 --tag $release --name "pi64-buster-$version.zip" --file "pi64-$version.zip" || echo "${version} release error"
done
