#!/usr/bin/env bash

set -ex

cd build

release=$(date +"%Y-%m-%d")

git tag $release
git push origin $release

github-release release --user khs1994 --repo pi64 --tag $release --draft

for version in "lite" "desktop" ; do
    github-release upload --user khs1994 --repo pi64 --tag $release --name "pi64-$version.zip" --file "build/pi64-$version.zip" || echo "${version} release error"
done
