#!/usr/bin/env bash

set -ex

cd build

source .env

release=$(date +"%Y-%m-%d")-kernel-${kernelversion}

git tag $release || true
git push origin $release || true

github-release release --user ${GITHUB_USER:-khs1994} --repo pi64 --tag $release --draft || true

github-release upload --user ${GITHUB_USER:-khs1994} --repo pi64 --tag $release --name "linux-${kernelversion}.tar.gz" --file "linux.tar.gz" || true
github-release upload --user ${GITHUB_USER:-khs1994} --repo pi64 --tag $release --name "linux-${kernelversion}.tar.gz.sig" --file "linux.tar.gz.sig" || true
