#!/usr/bin/env bash

set -x

deb_packages=$(pi64-build -deb_packages -version lite)

echo "[General]
# noauth=true
unpack=true
allowrecommends=true
debootstrap=Debian
aptsources=Debian

[Debian]
source=http://cdn-fastly.deb.debian.org/debian
keyring=debian-archive-keyring
components=main contrib non-free
suite=buster
packages=${deb_packages}"> ./multistrap.config

cat multistrap.config

mkdir -p ./build/root-lite
multistrap -a arm64 -d build/root-lite -f multistrap.config
rm -rf build/*
