on:
  push

name: CI

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          sudo apt-get update \
          && sudo apt-get -y install \
          bc \
          build-essential \
          cmake \
          device-tree-compiler \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          git \
          unzip \
          qemu-user-static \
          multistrap \
          zip \
          wget \
          dosfstools \
          kpartx \
          rsync \
          && go get \
          github.com/aktau/github-release \
          github.com/cheggaaa/pb \
          golang.org/x/crypto/openpgp
      - run: |
          set -x
          go version
          go env
          export GOPATH=$HOME/go
          go env
          mkdir -p $GOPATH/src/github.com/bamarni/pi64  
          cp -a . $GOPATH/src/github.com/bamarni/pi64
          go install github.com/bamarni/pi64/cmd/pi64-build
          export PATH=$GOPATH/bin:$PATH
          cd $GOPATH/src/github.com/bamarni/pi64
          make all
