on:
  push:
  pull_request:

name: CI

jobs:
  build:
    name: Build-Dist-Buster
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          sudo apt-get update \
          && sudo apt-get -y install \
          bc \
          build-essential \
          cmake \
          device-tree-compiler \
          gcc-aarch64-linux-gnu \
          g++-aarch64-linux-gnu \
          git \
          unzip \
          qemu-user-static \
          multistrap \
          zip \
          wget \
          dosfstools \
          kpartx \
          rsync \
          flex bison libssl-dev gnupg2 \
          && go get \
          github.com/aktau/github-release \
          github.com/cheggaaa/pb \
          golang.org/x/crypto/openpgp
        name: Install deps
      - run: |
          set -x
          go version
          go env
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH
          test -n "$GITHUB_TOKEN" && echo 0 || echo 1
          sudo go env || true
          sudo go version || true
          mkdir -p $GOPATH/src/github.com/bamarni/pi64
          cp -a . $GOPATH/src/github.com/bamarni/pi64
          go install github.com/bamarni/pi64/cmd/pi64-build
          ls -la $HOME/go/bin || true
          sudo ln -s $HOME/go/bin/pi64-build /usr/bin || true
          sudo pi64-build || true
          sudo rm -rf build
        name: Setup Env
      - run: |
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH
          cd $(go env GOPATH)/src/github.com/bamarni/pi64

          echo "[General]
          # noauth=true
          unpack=true
          allowrecommends=true
          debootstrap=Debian
          aptsources=Debian

          [Debian]
          source=http://cdn-fastly.deb.debian.org/debian
          keyring=debian-archive-keyring
          components=main contrib non-free
          suite=buster
          packages=apt systemd systemd-sysv udev kmod locales sudo netbase net-tools ethtool iproute2 iputils-ping ifupdown dhcpcd5 firmware-brcm80211 wpasupplicant ntp dialog wireless-tools parted ca-certificates ssh avahi-daemon"> ./multistrap.config

          cat multistrap.config

          mkdir -p ./build/root-lite
          multistrap -a arm64 -d build/root-lite -f multistrap.config || sudo multistrap -a arm64 -d build/root-lite -f multistrap.config

          sudo rm -rf build
        name: Test cli
      - run: |
          set -x
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH
          cd $(go env GOPATH)/src/github.com/bamarni/pi64

          sudo make build/pi64-lite.zip
        name: Build
      - run: |
          set -x
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH
          cd $(go env GOPATH)/src/github.com/bamarni/pi64

          ls -la build
        name: Show Build Dir
      - run: |
          set -x
          export GOPATH=$HOME/go
          export PATH=$GOPATH/bin:$PATH
          cd $(go env GOPATH)/src/github.com/bamarni/pi64

          sudo chown `id -u`:`id -g` build

          test -n "$GITHUB_TOKEN" && echo 0 || echo 1
          git remote set-url origin https://${GITHUB_USER:-khs1994}:${GITHUB_TOKEN:?must set}@github.com/${GITHUB_USER:-khs1994}/pi64
          make release
          make release/kernel
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_USER: khs1994
        name: Release
        if: github.event_name == 'push'
  # docker-build:
  #   name: Docker-Build-Dist-Buster
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push'
  #   env:
  #     GITHUB_TOKEN: ${{ github.token }}
  #     GITHUB_USER: khs1994
  #   steps:
  #     - uses: actions/checkout@master
  #       with:
  #         fetch-depth: 1
  #     - uses: docker-practice/actions-setup-docker@master
  #     - run: git remote set-url origin https://${GITHUB_USER:-khs1994}:${GITHUB_TOKEN:?must set}@github.com/${GITHUB_USER:-khs1994}/pi64
  #     - run: docker build -t pi64 .
  #     - run: mkdir -p build
  #     - run: docker run -t --rm -v $PWD/build:/go/src/github.com/bamarni/pi64/build pi64
  #     - run: ls -la build/*
  #     - run: docker run -t --rm -v $PWD/build:/go/src/github.com/bamarni/pi64/build -e GITHUB_TOKEN pi64 release
  #       if: github.event_name == 'push'
  #     - run: docker run -t --rm -v $PWD/build:/go/src/github.com/bamarni/pi64/build -e GITHUB_TOKEN pi64 release/kernel
  #       if: github.event_name == 'push'
