on:
  push:
  pull_request:

name: CI

jobs:
  build:
    name: Docker-Build-Dist-Buster
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' &&
      ! (contains( github.event.head_commit.message, '[skip ci]')
      || contains( github.event.head_commit.message, '[skip action]')
      || contains( github.event.head_commit.message, '[ci skip]')
      || contains( github.event.head_commit.message, '[action skip]'))
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_USER: khs1994
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: docker-practice/actions-setup-docker@master
      - run: git remote set-url origin https://${GITHUB_USER:-khs1994}:${GITHUB_TOKEN:?must set}@github.com/${GITHUB_USER:-khs1994}/pi64
      - run: docker build -t pi64 .
      - run: mkdir -p build
      - run: docker run -t --privileged --rm pi64 ls -la
      - run: docker run -t --privileged --rm -e GITHUB_USER -v $PWD/build:/go/src/github.com/bamarni/pi64/build pi64 make test
      - run: docker run -t --privileged --rm -e GITHUB_USER -v $PWD/build:/go/src/github.com/bamarni/pi64/build pi64 make build/pi64-lite.zip
      - run: ls -la build/*
      - run: docker run -t --rm -v $PWD/build:/go/src/github.com/bamarni/pi64/build -e GITHUB_TOKEN -e GITHUB_USER pi64 make release
      - run: docker run -t --rm -v $PWD/build:/go/src/github.com/bamarni/pi64/build -e GITHUB_TOKEN -e GITHUB_USER pi64 make release/kernel
