on:
  push:
  pull_request:

name: CI

jobs:
  build:
    name: Docker-Build-Dist-Stretch
    runs-on: ubuntu-latest
    if: |
      ! (contains( github.event.head_commit.message, '[skip ci]')
      || contains( github.event.head_commit.message, '[skip action]')
      || contains( github.event.head_commit.message, '[ci skip]')
      || contains( github.event.head_commit.message, '[action skip]'))
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GITHUB_USER: khs1994
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: docker-practice/actions-setup-docker@master
      - run: git remote set-url origin https://${GITHUB_USER:-khs1994}:${GITHUB_TOKEN:?must set}@github.com/${GITHUB_USER:-khs1994}/pi64
      - run: docker build -t pi64 .
      - run: docker run -t --privileged --rm -v $PWD:/go/src/github.com/bamarni/pi64 pi64 make get/linux
      - run: docker run -t --privileged --rm -v $PWD:/go/src/github.com/bamarni/pi64 pi64 ls -la build
      - run: sudo ls -la build
      - run: docker run -t --privileged --rm -e GITHUB_USER -v $PWD:/go/src/github.com/bamarni/pi64 pi64 make test
      - run: docker run -t --privileged --rm -e GITHUB_USER -v $PWD:/go/src/github.com/bamarni/pi64 pi64 make build/pi64-lite.zip
      - run: ls -la build/*
      - run: docker run -t --privileged --rm -v $PWD:/go/src/github.com/bamarni/pi64 -e GITHUB_TOKEN -e GITHUB_USER pi64 make release
        if: github.event_name == 'push'
      # - run: docker run -t --privileged --rm -v $PWD:/go/src/github.com/bamarni/pi64 -e GITHUB_TOKEN -e GITHUB_USER pi64 make release/kernel
        # if: github.event_name == 'push'
